spring.application.name=auth service

server.port=8080



spring.datasource.url=jdbc:mysql://localhost:3306/db_myapp
spring.datasource.username=root
spring.datasource.password=root@1234


spring.session.store-type=jdbc
# Optional: Customize schema initialization (embedded is default for H2, 'always' or 'never' for other DBs)
spring.session.jdbc.initialize-schema=always 
# Optional: Customize session timeout

server.servlet.session.timeout=30m

spring.jpa.hibernate.ddl-auto=update

spring.output.ansi.enabled=ALWAYS


logging.level.org.springframework.security=DEBUG